# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:08
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 28, 17, 8, 41, 308055, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
