# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160728_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combiner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
